Develop
ClevertecFrontendLab/sprint1-artemshaf pull request #2
Opened 2023-01-23 17:14 UTC by artemshaf

2023-01-23 17:18 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/book-page%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/book-page%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/book-page.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/content-list%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/content-list%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/content-list.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/content-window%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/content-window%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674494292/content-window.png)

2023-01-23 17:58 UTC, Gaurrus requested changes

2023-01-23 17:58 UTC, Gaurrus commented on react-cli-templates/component/TemplateName.module.scss
> +}
По заданию нужна глобальная доработка адаптивной верстки 
![image](https://user-images.githubusercontent.com/85307211/214112857-0bda569f-452e-44aa-adb0-95f4e003a62f.png)
такая 
![image](https://user-images.githubusercontent.com/85307211/214113228-2eb2bb21-9058-4455-99ea-c8bd5b398fcd.png)
и такая верстка
![image](https://user-images.githubusercontent.com/85307211/214113519-307d5005-58cc-4b3a-84ea-ca7a39525aa1.png)
![image](https://user-images.githubusercontent.com/85307211/214113834-bb276816-e6e3-4695-8241-03caed733ffa.png)
пустое пространство до футера - не годится. 
Так же добавлено много компонентов не относящихся к заданию спринта, думать на будущее это хорошо, но в результате видно что нужно было уделить время другим моментам =)

2023-01-23 19:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/book-page%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/book-page%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/book-page.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/content-list%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/content-list%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/content-list.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/content-window%20320px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/content-window%20768px.png)
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/artemshaf/1674501413/content-window.png)

2023-01-23 22:56 UTC, ValadzkoAliaksei approved these changes

2023-01-24 06:16 UTC, Gaurrus approved these changes

2023-01-24 06:16 UTC, Gaurrus commented on .eslintrc.js
>  module.exports = {
![image](https://user-images.githubusercontent.com/85307211/214224302-9baf8aab-3a8c-4dd4-bcbb-5d5cd2e27a38.png)
цвет вот тут посмотри

2023-01-24 06:19 UTC, merged